Exercício 1 CRIAR UM PROGRAMA BASE PARA RECEBER OS INCLUDS 
O PROGRAMA DEVE TER 4 PARAMETERS
	P_VAL1 TYPE I
	P_VAL2 TYPE I
	P_VAL3 TYPE I
	P_VAL4 TYPE I
	E UM  
	P_RESU TYPE P DECIMALS 2 NO-DISPLAY. "NÃO EXIBE ESSE CAMPO NA TELA
	
DEPIS CRIAR RADIOBUTTONs PARA CADA TIPO DE OPERACAO QUE IREMOS FAZER 
		MEDIA, SOMA, SUBTRACAO, MULTIPLICACAO E DIVISAO

EXEMPLO: PARAMETERS: P_MEDIA RADIOBUTTON GROUP  OPC,
					 P_SOMA  RADIOBUTTON GROUP  OPC.

VALIDAR QUAL RADIOBUTTON GROUP  FOI SELECIONADO E CRIAR UM PERFORM PASSANDO VALOR RESGATADO NA TELA
IF	P_MEDIA EQ ABAP_TRUE.
	PERFORM F_MEDIA USING P_VAL1 P_VAL2 P_RESU.
ENDIF.

E FAZER A LOGICA DE CADA OPERACAO COM UM MESSAGE NO FINAL MOSTRANDO O RESULTADO


EXERCÍCIO 2: CÁLCULO DA ÁREA DE UM RETÂNGULO (PASSAGEM DE PARÂMETRO)

OBJETIVO: CRIAR UM PROGRAMA QUE CALCULA A ÁREA DE UM RETÂNGULO UTILIZANDO UM PERFORM PARA REALIZAR O CÁLCULO.
REQUISITOS:
O PROGRAMA DEVE SOLICITAR AO USUÁRIO QUE INSIRA A BASE E A ALTURA DO RETÂNGULO.
UTILIZAR UM PERFORM PARA CALCULAR A ÁREA, PASSANDO A BASE E A ALTURA COMO PARÂMETROS.
EXIBIR O RESULTADO DA ÁREA NA TELA.

EXERCÍCIO 3: CRIAR UM PROGRAMA PARA CALCULAR 10% DE DESCONTO COM CODIGO 'ABAP10'
OBJETIVO: CRIARA UM PROGRAMA  PARA VALIDAR SE O CODIGO 'ABAP10' FOI DIGITADO NO PARAMETER E CHAMAR UM FORM PASSANDO Por Referência O VALOR TOTAL
		  E ESCREVER TA TELA O VALOR FINAL DA COMPRA.