*&---------------------------------------------------------------------*
*& Include          ZCSAN_CONTROLE_ESCOLAR_SOS
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF SCREEN 101 AS SUBSCREEN.

  SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

  PARAMETERS: P_NOME TYPE ZCSAN_TAB_ALUNO-NOME_ALUNO,
              P_MAT TYPE ZCSAN_TAB_ALUNO-MATRICULA,
              P_TURMA TYPE ZCSAN_TAB_ALUNO-ID_TURMA,
              P_NOTA1 TYPE ZCSAN_TAB_ALUNO-NOTA_1B,
              P_NOTA2 TYPE ZCSAN_TAB_ALUNO-NOTA_2B,
              P_NOTA3 TYPE ZCSAN_TAB_ALUNO-NOTA_3B,
              P_NOTA4 TYPE ZCSAN_TAB_ALUNO-NOTA_4B,
              P_STATUS TYPE ZCSAN_TAB_ALUNO-STATUS_ALUNO.

SELECTION-SCREEN SKIP 1.

SELECTION-SCREEN BEGIN OF LINE.

  PARAMETERS: B_ADD_A RADIOBUTTON GROUP OPC1.
              SELECTION-SCREEN COMMENT 3(10) ADD.

               PARAMETERS: B_ATU_A RADIOBUTTON GROUP OPC1.
              SELECTION-SCREEN COMMENT 16(10) ATU.

               PARAMETERS: B_DEL_A RADIOBUTTON GROUP OPC1.
              SELECTION-SCREEN COMMENT 29(10) DEL.

               PARAMETERS: B_EXIB_A RADIOBUTTON GROUP OPC1.
              SELECTION-SCREEN COMMENT 42(10) EXIB.

SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN END OF BLOCK B1.

  SELECTION-SCREEN END OF SCREEN 101.


  "--------------------------------TELA DE SELEÇÃO DO PROFESSOR -------------------------------------------


  SELECTION-SCREEN BEGIN OF SCREEN 102 AS SUBSCREEN.

  SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002.

  PARAMETERS: P_NOME_P TYPE ZCSAN_TAB_PROF-NOME_PROFESSOR,
              P_ID_P TYPE ZCSAN_TAB_PROF-ID_PROFESSOR,
              P_MAT_P TYPE ZCSAN_TAB_PROF-MATERIA.




SELECTION-SCREEN SKIP 1.

SELECTION-SCREEN BEGIN OF LINE.

  PARAMETERS: B_ADD_P RADIOBUTTON GROUP OPC2.
              SELECTION-SCREEN COMMENT 3(10) ADD_P.

               PARAMETERS: B_ATU_P RADIOBUTTON GROUP OPC2.
              SELECTION-SCREEN COMMENT 16(10) ATU_P.

               PARAMETERS: B_DEL_P RADIOBUTTON GROUP OPC2.
              SELECTION-SCREEN COMMENT 29(10) DEL_P.

               PARAMETERS: B_EXIB_P RADIOBUTTON GROUP OPC2.
              SELECTION-SCREEN COMMENT 42(10) EXIB_P.

SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN END OF BLOCK B2.

  SELECTION-SCREEN END OF SCREEN 102.


  SELECTION-SCREEN BEGIN OF TABBED BLOCK T1 FOR 30 LINES.

    SELECTION-SCREEN TAB (30) TAB1 USER-COMMAND USRCMD1 DEFAULT SCREEN 101.
    SELECTION-SCREEN TAB (30) TAB2 USER-COMMAND USRCMD2 DEFAULT SCREEN 102.

    SELECTION-SCREEN END OF BLOCK T1.